name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use secret token
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          echo "Token is set but hidden in logs"
          echo "TOKEN=${TOKEN}" >> $GITHUB_ENV
